--- 
abstract: Parallel Goto-in-reverse
author: Audrey Tang <cpan@audreyt.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-ComeFrom
no_index: 
  directory: 
    - inc
    - t
provides: 
  Acme::ComeFrom: 
    file: lib/Acme/ComeFrom.pm
    version: 0.10
requires: 
  Filter::Simple: 0.7
  Hook::LexWrap: 0.2
  perl: 5.005
version: 0.10
