name: Acme-ComeFrom
version: 0.07
abstract: Parallel goto-in-reverse
author: Autrijus Tang (autrijus@autrijus.org)
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Filter::Simple: 0.70
  Hook::LexWrap: 0.20
no_index:
  directory:
    - inc
private:
  directory:
    - inc
generated_by: Module::Install version 0.27
